app/admin/forms.py
"""
Happy Cobra - Marirs
Skeleton of a Login & Registration system
MIT License
"""
from flask_wtf  import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, RadioField, TextAreaField, IntegerField, SelectMultipleField, FileField, SelectField
from wtforms.validators import InputRequired, Email, Length, DataRequired, NumberRange, EqualTo

#The admin happy-cobra form
class AdminLoginForm(FlaskForm):
    email = StringField('Email',validators=[InputRequired(),Email(message='Enter a valid email'), Length(max = 60)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=30)])
    remember = BooleanField('Remember me')

class EditUserForm(FlaskForm):
    firstname = StringField('Firstname',validators=[InputRequired(), Length(max = 20)])
    lastname = StringField('Lastname',validators=[InputRequired(), Length(max = 20)])

app/admin/__init__.py
"""
Happy Cobra - Marirs
Skeleton of a Login & Registration system
MIT License
"""

app/admin/routes.py
"""
Happy Cobra - Marirs
Skeleton of a Login & Registration system
MIT License
"""
from flask import Blueprint, render_template
from .forms import *
from flask_security import login_required, roles_required, roles_accepted


admin = Blueprint('admin', __name__, template_folder='templates')


@admin.route('/', methods=['GET', 'POST'])
@login_required
@roles_accepted('SuperAdmin', 'Admin')
def admin_index():
    """Admin Index
    """
    return render_template('index.html')

app/admin/templates/admin_base.html
<!doctype html>
<html class="no-js h-100" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}Happy Cobra - Admin Interface{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="{{ url_for('static', filename='css/shards-dashboards.1.1.0.min.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/extras.1.1.0.min.css')}}">
        <script async defer src="https://buttons.github.io/buttons.js"></script>
    </head>
    <body class="h-100">
        <div class="container-fluid">
            <div class="row">
                <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
                    <div class="main-navbar">
                        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
                            <a class="navbar-brand w-100 mr-0" href="{{ url_for('admin.admin_index') }}" style="line-height: 25px;">
                                <div class="d-table m-auto">
                                    <span class="d-none d-md-inline ml-1"><strong>Happy Cobra Admin</strong></span>
                                </div>
                            </a>
                        </nav>
                    </div>
                    <form class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
                        <div class="input-group input-group-seamless ml-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="nav-wrapper">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ url_for('admin.admin_index') }}">
                                    <i class="material-icons">dashboard</i>
                                    <span>Dashboard</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ url_for('admin.admin_index') }}">
                                    <i class="material-icons">person</i>
                                    <span>Users</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </aside>
                <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
                     <div class="main-navbar sticky-top bg-white">
                        <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
                            <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
                                <div class="input-group input-group-seamless ml-3">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fas fa-search"></i>
                                        </div>
                                </div>
                            <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
                            </form>

                            <ul class="navbar-nav border-left flex-row ">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                        <img class="user-avatar rounded-circle mr-2" src="{{ url_for('static', filename='images/avatar.png')}}" alt="User Avatar" />
                                        <span class="d-none d-md-inline-block">{{ current_user.firstname }}</span>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-small">
                                        <a class="dropdown-item" href="#">
                                            <i class="material-icons">&#xE7FD;</i> Profile</a>
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item text-primary" href="{{ url_for('index') }}">
                                            <i class="material-icons">&#xE7FD;</i> User Page</a>
                                        </a>
                                        <a class="dropdown-item text-danger" href="{{ url_for_security('logout') }}">
                                            <i class="material-icons text-danger">&#xE879;</i> Logout </a>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                            <nav class="nav">
                                <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                                    <i class="material-icons">&#xE5D2;</i>
                                </a>
                            </nav>
                        </nav>
                    </div>
                    {% block content %}
                    {% endblock %}
                    <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
                    <ul class="nav">
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Admin home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index') }}">User Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for_security('logout') }}">Logout</a>
                      </li>
                    </ul>
                    <span class="copyright ml-auto my-auto mr-2">Copyright © 2018
                      <a href="https://designrevision.com" rel="nofollow">DesignRevision</a>
                    </span>
                    </footer>
               </main>
            </div>

        </div>
        {% block footer %}
        {% endblock %}
        {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
        <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
        <script src="{{ url_for('static', filename='js/admin/extras.1.1.0.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/admin/shards-dashboards.1.1.0.min.js')}}"></script>
        <script src="{{ url_for('static', filename='js/admin/app-overview.1.1.0.js')}}"></script>
        {% endblock %}
    </body>
</html>

app/admin/templates/index.html
{% extends "admin_base.html" %}

{% block content %}
                <div class="main-content-container container-fluid px-4">
                    <div class="page-header row no-gutters py-4">
                        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                            <span class="text-uppercase page-subtitle">Dashboard</span>
                            <h3 class="page-title">Overview</h3>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-lg col-md-6 col-sm-6 mb-4">
                        <div class="stats-small stats-small--1 card card-small">
                          <div class="card-body p-0 d-flex">
                            <div class="d-flex flex-column m-auto">
                              <div class="stats-small__data text-center">
                                <span class="stats-small__label text-uppercase">Super Admins</span>
                                <h6 class="stats-small__value count my-3">2,390</h6>
                              </div>
                              <div class="stats-small__data">
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg col-md-6 col-sm-6 mb-4">
                        <div class="stats-small stats-small--1 card card-small">
                          <div class="card-body p-0 d-flex">
                            <div class="d-flex flex-column m-auto">
                              <div class="stats-small__data text-center">
                                <span class="stats-small__label text-uppercase">Admins</span>
                                <h6 class="stats-small__value count my-3">2,390</h6>
                              </div>
                              <div class="stats-small__data">
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg col-md-6 col-sm-6 mb-4">
                        <div class="stats-small stats-small--1 card card-small">
                          <div class="card-body p-0 d-flex">
                            <div class="d-flex flex-column m-auto">
                              <div class="stats-small__data text-center">
                                <span class="stats-small__label text-uppercase">Users</span>
                                <h6 class="stats-small__value count my-3">2,390</h6>
                              </div>
                              <div class="stats-small__data">
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                </div>
{% endblock %}